services:
  postgres:
    image: postgres:16
    container_name: hiresphere-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: hiresphere_user
      POSTGRES_PASSWORD: hiresphere_pass
      POSTGRES_DB: hiresphere_dev
    ports:
      - "5432:5432"
    volumes:
      - hiresphere_pg_data:/var/lib/postgresql/data

volumes:
  hiresphere_pg_data: